# Generated by Django 2.2.6 on 2019-11-01 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('description', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=50)),
                ('director', models.CharField(max_length=50)),
                ('based_on', models.CharField(max_length=50)),
                ('main_actor', models.CharField(max_length=50)),
                ('release_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
